/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apud;

import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Adriano
 */
public class TelaInicial extends javax.swing.JFrame implements StatusUpdateInterface, TableUpdateInterface {

    private PresencaTableModel ptm;
    private PastaPDFParser parser;
    private Thread t;
    private HistoricoListModel hlm;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        parser = null;
        ptm = new PresencaTableModel();
        hlm = new HistoricoListModel();
        initComponents();
        tabela.setAutoCreateRowSorter(true);

        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/busca.png")).getImage());
        
        tabela.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    Presenca p = ((PresencaTableModel) table.getModel()).getPresenca(table.convertRowIndexToModel(table.getSelectedRow()));
                    new TelaDetalhes(p);
                }
            }
        });

        termos.getEditor().getEditorComponent().addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {

            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (pesquisar.isEnabled()) {
                        pesquisar.doClick();
                    }
                }
            }
        });

    }

    private File showOpenDirectoryDialog() {
        Preferences pref = Preferences.userRoot().node(TelaInicial.class.getName());
        JFileChooser chooser = new JFileChooser();
        String path = pref.get("defaultDir", ".");
        chooser.setCurrentDirectory(new java.io.File(path));
        chooser.setDialogTitle("Choose folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            pref.put("defaultDir", chooser.getSelectedFile().getParentFile().getAbsolutePath());
            return chooser.getSelectedFile();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        percentual = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        termos = new javax.swing.JComboBox<>(hlm);
        jPanel4 = new javax.swing.JPanel();
        pasta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        ler = new javax.swing.JButton();
        sinonimos = new javax.swing.JCheckBox();
        regex = new javax.swing.JCheckBox();
        stop = new javax.swing.JButton();
        recursivo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("apud/Bundle"); // NOI18N
        setTitle(bundle.getString("TelaInicial.title")); // NOI18N

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("TelaInicial.jPanel2.border.title"))); // NOI18N

        percentual.setMinimum(1);
        percentual.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                percentualStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(percentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(percentual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("TelaInicial.jPanel3.border.title"))); // NOI18N
        jPanel3.setToolTipText(bundle.getString("TelaInicial.jPanel3.toolTipText")); // NOI18N

        termos.setEditable(true);
        termos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termosActionPerformed(evt);
            }
        });
        termos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                termosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                termosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(termos, 0, 281, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(termos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("TelaInicial.jPanel4.border.title"))); // NOI18N

        pasta.setEditable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/folder.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pasta, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/zoom.png"))); // NOI18N
        pesquisar.setText(bundle.getString("TelaInicial.pesquisar.text")); // NOI18N
        pesquisar.setEnabled(false);
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("TelaInicial.jLabel1.text")); // NOI18N

        status.setText(bundle.getString("TelaInicial.status.text")); // NOI18N

        ler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/report.png"))); // NOI18N
        ler.setText(bundle.getString("TelaInicial.ler.text")); // NOI18N
        ler.setEnabled(false);
        ler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lerActionPerformed(evt);
            }
        });

        sinonimos.setText(bundle.getString("TelaInicial.sinonimos.text")); // NOI18N

        regex.setText(bundle.getString("TelaInicial.regex.text")); // NOI18N
        regex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regexActionPerformed(evt);
            }
        });

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stop.png"))); // NOI18N
        stop.setEnabled(false);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        recursivo.setText(bundle.getString("TelaInicial.recursivo.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ler)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sinonimos)
                    .addComponent(regex)
                    .addComponent(recursivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sinonimos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recursivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regex))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesquisar)
                            .addComponent(stop)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ler)
                                .addComponent(jLabel1)
                                .addComponent(status)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        tabela.setModel(ptm);
        tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabela);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        ptm.limpa();
        t = new Thread(new Runnable() {
            @Override
            public void run() {
                stop.setEnabled(true);
                percentual.setEnabled(false);
                pesquisar.setEnabled(false);
                updateStatus("Searching for synonyms...");
                Sinonimos[] sinos = geraSinonimos();
                updateStatus("Synonyms vector ready. Searching...");
                parser.setPercentualMinimo(percentual.getValue());
                parser.setRegex(regex.isSelected());
                parser.realizaBusca(sinos);
                updateStatus("Done searching!");
                pesquisar.setEnabled(true);
                percentual.setEnabled(true);
                stop.setEnabled(false);
            }
        });
        t.start();
    }//GEN-LAST:event_pesquisarActionPerformed

    private void lerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lerActionPerformed
        TelaInicial referencia = this;
        t = new Thread(new Runnable() {                 //thread para varredura, processo concorrente ao
            @Override                                   //swing para não travar interface durante leitura
            public void run() {
                ler.setEnabled(false);
                File p = new File(pasta.getText());
                if (p.isDirectory()) {
                    updateStatus("Parsing PDF files...");
                    parser = new PastaPDFParser(p, referencia, referencia, recursivo.isSelected());
                } else {
                    JOptionPane.showMessageDialog(referencia, "The selected folder is not valid.");
                }
                updateStatus("Parsing complete.");
                pesquisar.setEnabled(parser != null);
                ler.setEnabled(true);
            }
        });
        t.start();
    }//GEN-LAST:event_lerActionPerformed

    // faz a verradura de arquivos
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File f = showOpenDirectoryDialog();
        if (f != null && f.isDirectory()) {
            pasta.setText(f.getAbsolutePath());
            ler.setEnabled(true);
        } else {
            pasta.setText("");
            ler.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regexActionPerformed
        if (regex.isSelected()) {
            sinonimos.setSelected(false);
            sinonimos.setEnabled(false);
        } else {
            sinonimos.setEnabled(true);
        }
    }//GEN-LAST:event_regexActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        t.stop();
        t = null;
        updateStatus("Process canceled!");
        pesquisar.setEnabled(true);
        percentual.setEnabled(true);
        stop.setEnabled(false);

    }//GEN-LAST:event_stopActionPerformed

    private void percentualStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_percentualStateChanged
        updateStatus("Minimum revelance set to " + percentual.getValue());
    }//GEN-LAST:event_percentualStateChanged

    private void termosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_termosKeyReleased

    }//GEN-LAST:event_termosKeyReleased

    private void termosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_termosKeyPressed

    }//GEN-LAST:event_termosKeyPressed

    private void termosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termosActionPerformed

    private Sinonimos[] geraSinonimos() {
        String pesquisa = (String) termos.getSelectedItem();
        String[] palavras = pesquisa.split("\\s");
        hlm.addHistorico(pesquisa);
        Sinonimos[] s = new Sinonimos[palavras.length];
        for (int i = 0; i < palavras.length; i++) {
            if (sinonimos.isSelected()) {
                palavras[i] = palavras[i].replace('_', ' ');
                updateStatus("Searching for synonyms: '" + palavras[i] + "'... ");
                s[i] = new Sinonimos(palavras[i]);
                updateStatus("Searching for synonyms: '" + palavras[i] + "'... done");
            } else {
                palavras[i] = palavras[i].replace('_', ' ');
                s[i] = new Sinonimos(palavras[i], false);
            }
        }
        return s;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton ler;
    private javax.swing.JTextField pasta;
    private javax.swing.JSlider percentual;
    private javax.swing.JButton pesquisar;
    private javax.swing.JCheckBox recursivo;
    private javax.swing.JCheckBox regex;
    private javax.swing.JCheckBox sinonimos;
    private javax.swing.JLabel status;
    private javax.swing.JButton stop;
    private javax.swing.JTable tabela;
    private javax.swing.JComboBox<String> termos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateStatus(String text) {
        status.setText(text);
    }

    @Override
    public void finishedProcessing() {
        pesquisar.setEnabled(true);
    }

    @Override
    public void updateTable(Presenca p) {
        ptm.adicionarRow(p);
    }
}
